### ISSUE TITLE
RVM not loaded correctly

### ISSUE THREAD

**Issue by dewyze** [dewyze/dotfiles#3]
@raymondberg rvm is not longer being loaded correctly.

```
Computer: [6.70G] ~ %
→ which ruby
/usr/bin/ruby
```

:confused:

**Comment by dewyze** [comment]
```
→ echo $PATH
/Users/john/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/john/.rvm/bin:/usr/local/heroku/bin
```

**Comment by dewyze** [comment]
(Also missing Postgres)

It's failing on `[[ ":$PATH:" != *":$1:"* ]]`.

**Comment by dewyze** [comment]
Correction, this is what fails `[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"`. I don't think that is being sourced?

**Comment by raymondberg** [comment]
Everything seems fine on my Yosemite box, what environment are you on?

**Comment by dewyze** [comment]
Fixed here: https://github.com/dewyze/dotfiles/commit/d92797459326027d1f7910cd306977711524df27

**Comment by raymondberg** [comment]
I <3 it.

**Comment by dewyze** [comment]
In bash we were sourcing it: https://github.com/dewyze/dotfiles/blob/edd58f2a5202c1cadc359b3c55a59b9c71a043cd/bashrc#L134

In zsh we were appending it to $PATH.

**Comment by raymondberg** [comment]
Explains why it worked on my box, I bash and then tmux into zsh
