### ISSUE TITLE
Airliner Is too good to let go

### ISSUE THREAD

**Issue by raymondberg** [dewyze/dotfiles#7]
We [hit a bug](http://stackoverflow.com/questions/23952127/tmux-colour-scheme-changes-when-opening-vim) in [the simplification](https://github.com/dewyze/dotfiles/pull/5) where airliner was replacing tmux configs.  We pulled the airliner stuff, but want to add it back later. 
### Dewzy:

Currently, when I start a tmux I see this:
<img width="423" alt="normal" src="https://cloud.githubusercontent.com/assets/1312168/12709908/4c5ed59a-c876-11e5-9662-ac1d90ed8807.png">

If I open vim after that I see this:
<img width="425" alt="normal vim" src="https://cloud.githubusercontent.com/assets/1312168/12709910/4ed6e9ac-c876-11e5-90c0-523d3dec571b.png">

In your refactor, if I open tmux I see this:
![rays](https://cloud.githubusercontent.com/assets/1312168/12709913/565f6fa0-c876-11e5-8b54-3c8b160849bd.png)

However, if I open vim in that same tmux, I see this:
![rays after vim](https://cloud.githubusercontent.com/assets/1312168/12709914/5a2058b6-c876-11e5-87d6-6c7d0da4c932.png)

I would think that none of this is right? I am not sure how it changes my tmux "back" to the old way when vim starts, but in the beginning looks...that different?

Thoughts?

**Comment by dewyze** [comment]
@raymondberg Thoughts on adding a `.tmuxline.local`? At least for me personally, between a `.vimrc.local` and using a `.tmuxline.local` someone could definitely customize their vim/tmux relationship while still using these files completely.

This would be an alternative doing os checking for installing fonts?

**Comment by raymondberg** [comment]
I think it's a good idea, minor comments outstanding on the branch.

**Comment by dewyze** [comment]
This now sources a `.tmuxline.conf.local` if available.
